const patterns = {
    adventure: / ADV /i,
    anniversary: / ANNIV /i,
    artist: /\(A\)/i,
    artistAndCoverArtist: /\(A\/CA\)/i,
    blackAndWhite: / B&W /i,
    blankCover: / BLANK (CVR|COVER) /i,
    collection: / COLL /i,
    cosplay: / COSPLAY /i,
    cosplayPhotoCover: / COSPLAY PHOTO (CVR|COVER) /i,
    cover: / (CVR|CV) /i,
    coverArtist: /\(CA\)/i,
    coverAsEnd: / (CVR|CV) $/i,
    coverLetter: / (CVR|CV) [A-Z] /i,
    deluxe: / DLX /i,
    directMarket: / DM /i,
    edition: / ED /i,
    editionWithParen: / ED\) /i,
    formatNumber: / \d+ /i,
    formatType: / (VOL|TP|HC|GN|BOOK|PART|OMNIBUS) /i,
    graphicNovel: / GN /i,
    graphicNovelHardcover: / GN HC /i,
    graphicNovelTradePaperbackVolumeWithNum: / GN TP VOL \d+ /,
    graphicNovelTradePaperbackWithNum: / GN TP \d+ /,
    graphicNovelVolumeWithNum: / GN VOL \d+ /,
    hardcover: / HC /i,
    hardcoverBookWithNum: / HC BOOK \d+ /,
    hardcoverGraphicNovelVolumeWithNum: / HC GN VOL \d+ /,
    hardcoverGraphicNovelWithNum: / HC GN \d+ /,
    hardcoverPartWithNum: / HC PART \d+ /,
    hardcoverVolumeWithNum: / HC VOL \d+ /,
    hardcoverWithNum: / HC \d+ /,
    kingInBlack: / KIB /,
    leadingZeros: /\b0+/,
    letter: / [A-Z] /i,
    limited: / (LMT|LTD|LT) /i,
    mature: / \(MR\) /i,
    miniSeries: / \(OF \d+\) /i,
    miniSeriesInd: / \(OF /i,
    miniSeriesNumber: / \d+\) /i,
    more: / More /i,
    net: / \(NET\) /i,
    number: / #\d+ /,
    ofThe: / O\/T /i,
    omnibus: / OMNIBUS /i,
    omnibusHardcover: / OMNIBUS HC /i,
    omnibusHardcoverVolumeWithNum: / OMNIBUS HC VOL \d+ /,
    omnibusVolumeWithNum: / OMNIBUS VOL \d+ /,
    oneShot: / ONE SHOT /i,
    operatingAs: / \(O\/A\) /i,
    original: / ORIG /i,
    photo: / PHOTO /i,
    printing: / PTG /i,
    printingNum: / \d+[A-Z]+ /i,
    r: / \(R /i,
    reprint: / \(?NEW PTG\)? /i,
    reprintNew: / \(?NEW /i,
    reprintPrinting: / PTG\)? /i,
    resolicit: / \(RES\) /i,
    signature: / SGN /i,
    softcover: / SC /i,
    subsequentPrintingNum: / \d+[A-Z]+ PTG /i,
    theNextGeneration: / TNG /i,
    tradePaperback: / TP /i,
    tradePaperbackBookWithNum: / TP BOOK \d+ /,
    tradePaperbackPartWithNum: / TP PART \d+ /,
    tradePaperbackVolumeWithNum: / TP VOL \d+ /,
    tradePaperbackWithNum: / TP \d+ /,
    trailingParentheses: / \(C? /i,
    useOtherDiamondID: / \(USE [A-Z]{3}\d+\) /i,
    variant: / (VAR|VA) /i,
    variantWithType: / \w+ (VAR|VA) /i,
    volume: / VOL (\d+)? /i,
    years: / YRS /i,
    writer: /\(W\)/i,
}

module.exports = patterns
